/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        Components: typeof import('./src/components/index.vue')['default']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
        ElForm: typeof import('element-plus/es')['ElForm']
        ElIcon: typeof import('element-plus/es')['ElIcon']
        ElResult: typeof import('element-plus/es')['ElResult']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}
