/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
      DynamicMenu: typeof import('./../components/DynamicMenu.vue')['default']
      ElResult: typeof import('element-plus/es')['ElResult']
      ElStep: typeof import('element-plus/es')['ElStep']
      ElSteps: typeof import('element-plus/es')['ElSteps']
      ElTabPane: typeof import('element-plus/es')['ElTabPane']
      ElTabs: typeof import('element-plus/es')['ElTabs']
      FormDrawer: typeof import('./../components/FormDrawer.vue')['default']
      FullScreenLoading: typeof import('./../components/FullScreenLoading.vue')['default']
      FullScreenMode: typeof import('./../components/FullScreenMode.vue')['default']
      LanguageSwitching: typeof import('./../components/LanguageSwitching.vue')['default']
      LoginPageSwitch: typeof import('./../components/LoginPageSwitch.vue')['default']
      NButton: typeof import('naive-ui')['NButton']
      NDrawer: typeof import('naive-ui')['NDrawer']
      NDrawerContent: typeof import('naive-ui')['NDrawerContent']
      NDropdown: typeof import('naive-ui')['NDropdown']
      NInput: typeof import('naive-ui')['NInput']
      NInputGroup: typeof import('naive-ui')['NInputGroup']
      NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
      NTabPane: typeof import('naive-ui')['NTabPane']
      NTabs: typeof import('naive-ui')['NTabs']
      NTag: typeof import('naive-ui')['NTag']
      NTooltip: typeof import('naive-ui')['NTooltip']
      RouterLink: typeof import('vue-router')['RouterLink']
      RouterView: typeof import('vue-router')['RouterView']
  }
}
