/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DynamicMenu: typeof import('./../components/DynamicMenu.vue')['default']
      ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
      ElCol: typeof import('element-plus/es')['ElCol']
      ElDialog: typeof import('element-plus/es')['ElDialog']
      ElIcon: typeof import('element-plus/es')['ElIcon']
      ElResult: typeof import('element-plus/es')['ElResult']
      ElRow: typeof import('element-plus/es')['ElRow']
      ElStep: typeof import('element-plus/es')['ElStep']
      ElSteps: typeof import('element-plus/es')['ElSteps']
      FormDrawer: typeof import('./../components/FormDrawer.vue')['default']
      FullScreenLoading: typeof import('./../components/FullScreenLoading.vue')['default']
      FullScreenMode: typeof import('./../components/FullScreenMode.vue')['default']
      FullScreenSwitch: typeof import('../components/FullScreenMode.vue')['default']
      GlobalTooltip: typeof import('./../components/GlobalTooltip.vue')['default']
      GobalTooltip: typeof import('../components/GlobalTooltip.vue')['default']
      IconAntDesignFullscreenExitOutlined: typeof import('~icons/ant-design/fullscreen-exit-outlined')['default']
      IconAntDesignFullscreenOutlined: typeof import('~icons/ant-design/fullscreen-outlined')['default']
      IconAntDesignIdcardFilled: typeof import('~icons/ant-design/idcard-filled')['default']
      IconAntDesignTranslationOutlined: typeof import('~icons/ant-design/translation-outlined')['default']
      IconEpApple: typeof import('~icons/ep/apple')['default']
      IconEpavatar: typeof import('~icons/ep/avatar')['default']
      IconEpClose: typeof import('~icons/ep/close')['default']
      IconEpGoblet: typeof import('~icons/ep/goblet')['default']
      LanguageSwitching: typeof import('./../components/LanguageSwitching.vue')['default']
      LoginPageSwitch: typeof import('./../components/LoginPageSwitch.vue')['default']
      NButton: typeof import('naive-ui')['NButton']
      NCheckbox: typeof import('naive-ui')['NCheckbox']
      NDivider: typeof import('naive-ui')['NDivider']
      NDrawer: typeof import('naive-ui')['NDrawer']
      NDrawerContent: typeof import('naive-ui')['NDrawerContent']
      NDropdown: typeof import('naive-ui')['NDropdown']
      NIcon: typeof import('naive-ui')['NIcon']
      NInput: typeof import('naive-ui')['NInput']
      NInputGroup: typeof import('naive-ui')['NInputGroup']
      NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
      NPopover: typeof import('naive-ui')['NPopover']
      NTabPane: typeof import('naive-ui')['NTabPane']
      NTabs: typeof import('naive-ui')['NTabs']
      NTag: typeof import('naive-ui')['NTag']
      NTooltip: typeof import('naive-ui')['NTooltip']
      RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
